### ISSUE TITLE
Setting unknown property: nuffic\messente\SMS::throw_exception_on

### ISSUE THREAD

**Issue by fsc7** [Nuffic/yii2-messente#1]
I am receiving the following message:
exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: nuffic\messente\SMS::throw_exception_on' in /home/sites/www/vendor/yiisoft/yii2/base/Component.php:197 Stack trace: #0 /home/sites/www/vendor/yiisoft/yii2/BaseYii.php(518): yii\base\Component->__set('throw_exception...', Array) #1 /home/sites/www/vendor/yiisoft/yii2/base/Object.php(105): yii\BaseYii::configure(Object(nuffic\messente\SMS), Array) #2 [internal function]: yii\base\Object->__construct(Array) #3 /home/sites/www/vendor/yiisoft/yii2/di/Container.php(372): ReflectionClass->newInstanceArgs(Array) #4 /home/sites/www/vendor/yiisoft/yii2/di/Container.php(151): yii\di\Container->build('nuffic\messente...', Array, Array) #5 

My config:
        'sms' => [
            'class'    => 'nuffic\messente\SMS',
            'username' => '0fc9223582427c7ed4508da3c9f4a820',
            'password' => 'dde6b7605d9b535660140e031fb9b56e',
        ],
My use case:
Yii::$app->sms->send('EE', 'Confirmation', '+3721111111', 'Messager');

**Comment by Nuffic** [comment]
Please search for `throw_exception_on` throughout the project. Where is it used?
As far as I know, there's no such thing in Yii and there's no such property in this project.

**Comment by fsc7** [comment]
Here is where it breaks:

```
1. in /home/sites/www/vendor/yiisoft/yii2/base/Component.php at line 197
$behavior->$name = $value;
                    return;
                }
            }
        }
        if (method_exists($this, 'get' . $name)) {
            throw new InvalidCallException('Setting read-only property: ' . get_class($this) . '::' . $name);
        } else {
            throw new UnknownPropertyException('Setting unknown property: ' . get_class($this) . '::' . $name);
        }
    }
```

It seems a problem with the constructor.

**Comment by Nuffic** [comment]
invalid

**Comment by fsc7** [comment]
Your message was not clear, I will try to figure out. Thanks anyway.
